name: Build & Deploy Spring app
on:
  push:
    branches:
      -main
jobs:
   build-deploy:
     name: Build and Deploy Spring boot
     runs-on: ubunto-lates
     steps:
       - name: Chekout code
       uses: actions/checkout@v3

       - name: Setup jdk 17
       uses: actions/setup-java@v3
       with:
         distribution: 'corretto'
         java-version: 17
       - name: Unit tests
         run: mvm -B test --file pom.xml
       - name: Build the application
         run:
           mvn clean
           mvn -B packege --file pom.xml


